/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2024-05-21 09:41:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.include;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/D:/yu/hwanpro03/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/pro3/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1714616544218L));
    _jspx_dependants.put("jar:file:/D:/yu/hwanpro03/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/pro3/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/yu/hwanpro03/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/pro3/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path2 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/footer.css\">\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>샘플 목록</title>\r\n");
      out.write("	<style>\r\n");
      out.write("	footer {\r\n");
      out.write("	    position: relative;\r\n");
      out.write("	    height: 180px;\r\n");
      out.write("	    padding: 30px 370px 32px 80px;\r\n");
      out.write("	    background: #ada8a8;\r\n");
      out.write("	    z-index: 16;\r\n");
      out.write("	    font-weight: 800;\r\n");
      out.write("	  }\r\n");
      out.write("	  \r\n");
      out.write("	  footer .footer_link {\r\n");
      out.write("	    margin-bottom: 10px;\r\n");
      out.write("	  }\r\n");
      out.write("	  \r\n");
      out.write("	  footer .footer_link a {\r\n");
      out.write("	    display: inline-block;\r\n");
      out.write("	    margin-right: 45px;\r\n");
      out.write("	    font-size: 16px;\r\n");
      out.write("	    font-weight: 400;\r\n");
      out.write("	    color: #181414;\r\n");
      out.write("	    line-height: 36px;\r\n");
      out.write("	  }\r\n");
      out.write("	  \r\n");
      out.write("	  footer .footer_link a.priv {\r\n");
      out.write("	    color: #0890c0;\r\n");
      out.write("	    font-weight: 700;\r\n");
      out.write("	  }\r\n");
      out.write("	  \r\n");
      out.write("	  footer .footer_link a:last-child {\r\n");
      out.write("	    margin-right: 0;\r\n");
      out.write("	  }\r\n");
      out.write("	  \r\n");
      out.write("	  footer .address {\r\n");
      out.write("	    font-size: 14px;\r\n");
      out.write("	    font-weight: 300;\r\n");
      out.write("	    color: #111010;\r\n");
      out.write("	    line-height: 30px;\r\n");
      out.write("	  }\r\n");
      out.write("	  \r\n");
      out.write("	  /* 2022-02-15 추가 */\r\n");
      out.write("	  footer .registration {\r\n");
      out.write("	    font-size: 14px;\r\n");
      out.write("	    font-weight: 300;\r\n");
      out.write("	    color: #111010;\r\n");
      out.write("	    line-height: 30px;\r\n");
      out.write("	  }\r\n");
      out.write("	  /* // 2022-02-15 추가 */\r\n");
      out.write("	  \r\n");
      out.write("	  footer .copy {\r\n");
      out.write("	    font-size: 12px;\r\n");
      out.write("	    font-weight: 300;\r\n");
      out.write("	    color: #050505;\r\n");
      out.write("	    line-height: 22px;\r\n");
      out.write("	    letter-spacing: 1px;\r\n");
      out.write("	  }\r\n");
      out.write("	  \r\n");
      out.write("	  footer .logo {\r\n");
      out.write("	    position: absolute;\r\n");
      out.write("	    top: 50%;\r\n");
      out.write("	    left: auto;\r\n");
      out.write("	    right: 80px;\r\n");
      out.write("	    width: 134px;\r\n");
      out.write("	    transform: translateY(-50%);\r\n");
      out.write("	    height: 34px;\r\n");
      out.write("	    background: url(\"../../common/images/footer-logo.png\") center no-repeat;\r\n");
      out.write("	    text-indent: -9999px;\r\n");
      out.write("	  }\r\n");
      out.write("	  \r\n");
      out.write("	  footer .link_selec {\r\n");
      out.write("	    position: absolute;\r\n");
      out.write("	    top: 80px;\r\n");
      out.write("	    right: 80px;\r\n");
      out.write("	    width: 240px;\r\n");
      out.write("	  }\r\n");
      out.write("	  \r\n");
      out.write("	  footer .link_selec .open {\r\n");
      out.write("	    display: block;\r\n");
      out.write("	    padding: 15px 0;\r\n");
      out.write("	    font-size: 16px;\r\n");
      out.write("	    font-weight: 300;\r\n");
      out.write("	    color: #333333;\r\n");
      out.write("	    line-height: 1;\r\n");
      out.write("	    letter-spacing: 0.4px;\r\n");
      out.write("	    background: url(\"../../common/images/select-icon2-on.png\") no-repeat right center;\r\n");
      out.write("	    border-bottom: 2px solid #000000;\r\n");
      out.write("	  }\r\n");
      out.write("	  \r\n");
      out.write("	  footer .link_selec .fam_link_div {\r\n");
      out.write("	    display: none;\r\n");
      out.write("	    position: absolute;\r\n");
      out.write("	    bottom: 0;\r\n");
      out.write("	    left: 0;\r\n");
      out.write("	    width: 100%;\r\n");
      out.write("	    padding: 14px 20px;\r\n");
      out.write("	    background: #000;\r\n");
      out.write("	  }\r\n");
      out.write("	  \r\n");
      out.write("	  footer .link_selec .fam_link_div > div a {\r\n");
      out.write("	    display: block;\r\n");
      out.write("	    padding-top: 26px;\r\n");
      out.write("	    font-size: 16px;\r\n");
      out.write("	    font-weight: 300;\r\n");
      out.write("	    color: #fff;\r\n");
      out.write("	    line-height: 1;\r\n");
      out.write("	  }\r\n");
      out.write("	  \r\n");
      out.write("	  footer .link_selec .fam_link_div > div a:first-child {\r\n");
      out.write("	    padding-top: 0;\r\n");
      out.write("	  }\r\n");
      out.write("	  \r\n");
      out.write("	  footer .link_selec .fam_link_div .close {\r\n");
      out.write("	    display: block;\r\n");
      out.write("	    position: absolute;\r\n");
      out.write("	    bottom: 14px;\r\n");
      out.write("	    right: 12px;\r\n");
      out.write("	    width: 80px;\r\n");
      out.write("	    height: 16px;\r\n");
      out.write("	    background: url(\"../../common/images/select-icon2-wht-on.png\") no-repeat center right;\r\n");
      out.write("	  }\r\n");
      out.write("	  \r\n");
      out.write("	  @media all and (max-width: 1500px) {\r\n");
      out.write("	    footer {\r\n");
      out.write("	      height: auto;\r\n");
      out.write("	      padding-left: 5%;\r\n");
      out.write("	    }\r\n");
      out.write("	    footer .logo {\r\n");
      out.write("	      right: 5%;\r\n");
      out.write("	    }\r\n");
      out.write("	  }\r\n");
      out.write("	  \r\n");
      out.write("	  @media all and (max-width: 1024px) {\r\n");
      out.write("	    footer .footer_link a {\r\n");
      out.write("	      margin-right: 15px;\r\n");
      out.write("	    }\r\n");
      out.write("	  }\r\n");
      out.write("	  \r\n");
      out.write("	  @media all and (max-width: 768px) {\r\n");
      out.write("	    footer {\r\n");
      out.write("	      height: auto;\r\n");
      out.write("	      padding: 34px 5%;\r\n");
      out.write("	    }\r\n");
      out.write("	    footer .footer_link {\r\n");
      out.write("	      margin-bottom: 12px;\r\n");
      out.write("	    }\r\n");
      out.write("	    footer .footer_link a {\r\n");
      out.write("	      margin: 0 26px 0 0;\r\n");
      out.write("	      line-height: 27px;\r\n");
      out.write("	      font-size: 13px;\r\n");
      out.write("	    }\r\n");
      out.write("	    footer .footer_link a:last-child {\r\n");
      out.write("	      margin-right: 0;\r\n");
      out.write("	    }\r\n");
      out.write("	    footer .link_selec {\r\n");
      out.write("	      display: none;\r\n");
      out.write("	    }\r\n");
      out.write("	    footer .address {\r\n");
      out.write("	      display: none;\r\n");
      out.write("	    }\r\n");
      out.write("	    /* 2022-02-15 추가 */\r\n");
      out.write("	    footer .registration {\r\n");
      out.write("	      font-size: 13px;\r\n");
      out.write("	    }\r\n");
      out.write("	    /* // 2022-02-15 추가 */\r\n");
      out.write("	    footer .copy {\r\n");
      out.write("	      font-size: 10px;\r\n");
      out.write("	      font-weight: 300;\r\n");
      out.write("	      color: #777;\r\n");
      out.write("	      line-height: 16px;\r\n");
      out.write("	    }\r\n");
      out.write("	    footer .logo {\r\n");
      out.write("	      display: none;\r\n");
      out.write("	    }\r\n");
      out.write("	  }\r\n");
      out.write("	</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<footer id=\"footer\" data-swiftype-index=\"false\">\r\n");
      out.write("        <hr>\r\n");
      out.write("        <div class=\"footer_link\">\r\n");
      out.write("            <a href=\"/business/overview/index.do\">기업정보</a>\r\n");
      out.write("            <a href=\"/etc/policy/use/view.do\">이용약관</a>\r\n");
      out.write("            <a href=\"/etc/policy/privacy/view.do\" class=\"priv\">개인정보처리방침</a>\r\n");
      out.write("            <a href=\"/etc/new-store/index.do\">매장개설안내</a>\r\n");
      out.write("            <a href=\"/etc/special-business/index.do\">특판사업</a>\r\n");
      out.write("            <a href=\"/customer/prdct-manual/index.do\">고객지원</a>\r\n");
      out.write("            <a href=\"javascript:cmmCtrl.loginCheckPage('/my-page/buy-auth/index.do')\">구매인증센터</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <hr>\r\n");
      out.write("        <p class=\"registration\">(주)에이스침대 / 사업자등록번호 : 129-81-02666</p> <!-- 2022-02-15 추가 -->\r\n");
      out.write("        <!-- 2021-02-16 수정 -->\r\n");
      out.write("        <p class=\"address\">본사 : 경기도 성남시 중원구 사기막골로 105번길 42(상대원동) / 서울영업본부 : 서울특별시 강남구 도산대로 218  / FAX : 02-544-8788</p>\r\n");
      out.write("        <!-- // 2021-02-16 수정 -->\r\n");
      out.write("\r\n");
      out.write("        <p class=\"copy\">COPYRIGHT (C) ACE BED <br class=\"only_mob\">CORPORATION ALL RIGHTS RESERVED</p>\r\n");
      out.write("        <div class=\"link_selec\">\r\n");
      out.write("            <div class=\"fam_link_div\">\r\n");
      out.write("                <div>\r\n");
      out.write("                    <a href=\"http://eng.acebed.com\" target=\"_blank\">ENGLISH</a>\r\n");
      out.write("                    <a href=\"http://www.aceavenue.co.kr\" target=\"_blank\">에이스 에비뉴</a>\r\n");
      out.write("                    <a href=\"http://www.aceheritz.com\" target=\"_blank\">에이스 헤리츠</a>\r\n");
      out.write("                    <a href=\"https://acebedmall.co.kr\" target=\"_blank\">에이스 침대몰</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <a href=\"javascript:\" class=\"close\"></a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <a href=\"javascript:\" class=\"open\">FAMILY SITE</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/include/footer.jsp(6,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("path2");
      // /WEB-INF/views/include/footer.jsp(6,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/include/footer.jsp(6,0) '${pageContext.request.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
